import { getPayload } from 'payload'
import config from '@/payload.config'
import React, { Suspense } from 'react'
import MedicalHistoryClient from './MedicalHistoryClient'
import { RegistrySkeleton } from '../components/RegistrySkeleton'
// Import the actual types generated by Payload
import { Appointment, Service } from '@/payload-types'
// Import the interface used by your Client Component
import { RawAppointment } from './MedicalHistoryClient'

export default async function MedicalHistoryPage({
  searchParams,
}: {
  searchParams: Promise<{ page?: string; search?: string }>
}) {
  const payload = await getPayload({ config })
  const params = await searchParams

  const currentPage = Number(params.page) || 1
  const search = params.search || ''

  const data = await payload.find({
    collection: 'appointments',
    pagination: false,
    where: search
      ? {
          or: [
            { firstName: { contains: search } },
            { surname: { contains: search } },
            { email: { contains: search } },
          ],
        }
      : {},
    sort: '-appointmentDate',
    depth: 1,
  })

  // 1. Cast the database docs to the generated Appointment type
  const appointments = data.docs as Appointment[]

  // 2. Map and sanitize without using 'any'
  // Explicitly typing the array as RawAppointment[] ensures it matches the Client Prop
  const sanitizedDocs: RawAppointment[] = appointments.map((doc) => {
    // Determine the service title safely
    let serviceTitle = 'General Procedure'

    if (doc.service && typeof doc.service === 'object') {
      // TypeScript knows doc.service is a 'Service' object here
      const service = doc.service as Service
      serviceTitle = service.title || 'General Procedure'
    } else if (typeof doc.service === 'string') {
      serviceTitle = doc.service
    }

    return {
      id: String(doc.id),
      firstName: doc.firstName,
      surname: doc.surname,
      email: doc.email,
      appointmentDate: doc.appointmentDate,
      status: doc.status as 'confirmed' | 'cancelled' | 'pending' | 'completed',
      isGuest: !!doc.isGuest,
      specialistNotes: doc.specialistNotes || '',
      service: serviceTitle,
    }
  })

  return (
    <Suspense fallback={<RegistrySkeleton />}>
      <MedicalHistoryClient initialData={sanitizedDocs} currentPage={currentPage} />
    </Suspense>
  )
}
